version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - mern-network

  frontend:
    build:
      context: ./frontend
    ports:
      - 8000:80
    networks:
      - mern-network


  # mongo:
  #   image:
  #     mongo:latest
  #   networks:
  #     - mern-network

networks:
  mern-network:
    driver: bridge
      